include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- build
- test
- deploy
- pages

.vars-devel:
  variables:
    MANIFEST_PATH: "org.gnome.libpanel.demo.json"
    FLATPAK_MODULE: "libpanel"
    APP_ID: "org.gnome.libpanel.demo"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "libpanel-dev.flatpak"

flatpak@x86_64:
  needs: []
  extends: ['.flatpak@x86_64', '.vars-devel']

flatpak@aarch64:
  needs: []
  extends: ['.flatpak@aarch64', '.vars-devel']

nightly@x86_64:
  extends: '.publish_nightly'
  needs: ['flatpak@x86_64']

nightly@aarch64:
  extends: '.publish_nightly'
  needs: ['flatpak@aarch64']

fedora:
  stage: build
  image: 'registry.fedoraproject.org/fedora:40'
  interruptible: true
  needs: []
  script:
    - sudo dnf -y install
            ccache
            desktop-file-utils
            editorconfig-devel
            enchant2-devel
            expat-devel
            gcc
            gcc-c++
            gettext
            gi-docgen
            git
            glib2-devel
            gobject-introspection-devel
            gtk4-devel
            itstool
            libadwaita-devel
            libicu-devel
            libjpeg-turbo-devel
            libpng-devel
            meson
            ninja-build
            redhat-rpm-config
            shared-mime-info
            xorg-x11-server-Xvfb
    - meson setup _build .
            -Ddocs=enabled
            -Dwerror=false
            -Dglib:werror=false
            -Dgtk:broadway-backend=false
            -Dgtk:build-examples=false
            -Dgtk:build-tests=false
            -Dgtk:demos=false
            -Dgtk:media-gstreamer=disabled
            -Dgtk:werror=false
            -Dicu:werror=false
            -Dlibadwaita:examples=false
            -Dlibadwaita:gtk_doc=false
            -Dlibadwaita:introspection=disabled
            -Dlibadwaita:tests=false
            -Dlibadwaita:vapi=false
            -Dlibadwaita:werror=false
            -Dlibsass:werror=false
            -Dpango:gtk_doc=false
            -Dpango:introspection=disabled
            -Dpango:werror=false
            -Dsassc:werror=false
            -Dwayland-protocols:tests=false
            -Dwayland:documentation=false
            -Dwayland:dtd_validation=false
            -Dwayland:tests=false
    - ninja -C _build test
    - mv _build/docs/panel-1.0 docs
  artifacts:
    paths:
    - docs

pages:
  stage: pages
  needs:
  - fedora
  script:
  - mv docs/panel-1.0 public
  artifacts:
    paths:
    - public
  only:
  - main
