include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- build
- test
- deploy
- pages

.vars-devel:
  variables:
    MANIFEST_PATH: "org.gnome.libpanel.demo.json"
    FLATPAK_MODULE: "libpanel"
    APP_ID: "org.gnome.libpanel.demo"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "libpanel-dev.flatpak"

flatpak@x86_64:
  needs: []
  extends: ['.flatpak@x86_64', '.vars-devel']

flatpak@aarch64:
  needs: []
  extends: ['.flatpak@aarch64', '.vars-devel']

nightly@x86_64:
  extends: '.publish_nightly'
  needs: ['flatpak@x86_64']

nightly@aarch64:
  extends: '.publish_nightly'
  needs: ['flatpak@aarch64']

fedora:
  stage: build
  image: 'registry.fedoraproject.org/fedora:39'
  interruptible: true
  needs: []
  script:
    - sudo dnf install -y meson gi-docgen gettext gcc git gtk4-devel libadwaita-devel
    - meson build -Ddocs=enabled
    - ninja -C build test
    - mv build/docs/panel-1.0 docs
  artifacts:
    paths:
    - docs

pages:
  stage: pages
  needs:
  - fedora
  script:
  - mv docs/panel-1.0 public
  artifacts:
    paths:
    - public
  only:
  - main