include:
  - project: "gnome/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      dist-job-name: "flatpak@x86_64"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"
  - component: "gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master"
  - component: "gitlab.gnome.org/GNOME/citemplates/basic-deploy-docs@master"

variables:
  FLATPAK_MODULE: "libpanel"
  TARBALL_ARTIFACT_PATH: ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

.vars-devel:
  variables:
    MANIFEST_PATH: "org.gnome.libpanel.demo.json"
    APP_ID: "org.gnome.libpanel.demo"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "libpanel-dev.flatpak"

flatpak@x86_64:
  needs: []
  extends: ['.flatpak@x86_64', '.vars-devel']

flatpak@aarch64:
  needs: []
  extends: ['.flatpak@aarch64', '.vars-devel']

nightly@x86_64:
  extends: '.publish_nightly'
  needs: ['flatpak@x86_64']

nightly@aarch64:
  extends: '.publish_nightly'
  needs: ['flatpak@aarch64']
